---
title: "Clustering"
author: "Vivek"
date: "4/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Clear environment
rm(list = ls())


### Create Simulated Data ###

set.seed (2)
x <- matrix(rnorm(100*2), ncol=2)
x[1:25,1]=x[1:25,1]+3
x[25:50,2]=x[25:50,2]-4
x[50:75,1]=x[50:75,1]+8
x[75:100,2] = x[75:100,2] -6

simData <- as.data.frame(x)
colnames(simData) <- c("X1", "X2")
simData$ID <- seq(1,100,1)
simData$truecluster <- rep(c("a","b","c","d"), each = 25)

excludes <- names(simData) %in% c("ID","truecluster") #Index of columns to exclude from analysis

```

```{r}
### K-means clustering ###

# Reference: ISLR 10.5.1

df_km <- simData

df_km$km3 <- as.factor(kmeans(simData[!excludes],3,nstart=20)$cluster)
df_km$km4 <- as.factor(kmeans(simData[!excludes],4,nstart=20)$cluster)
df_km$km5 <- as.factor(kmeans(simData[!excludes],5,nstart=20)$cluster)
df_km$km6 <- as.factor(kmeans(simData[!excludes],6,nstart=20)$cluster)

library(ggplot2)

km3_plot <- ggplot(data= df_km, aes(x=X1, y=X2, color=km3)) + geom_point()
km4_plot <- ggplot(data= df_km, aes(x=X1, y=X2, color=km4)) + geom_point()
km5_plot <- ggplot(data= df_km, aes(x=X1, y=X2, color=km5))+ geom_point()
km6_plot <- ggplot(data= df_km, aes(x=X1, y=X2, color=km6))+ geom_point()

library(gridExtra)
grid.arrange(km3_plot, km4_plot, km5_plot, km6_plot)

```

```{r}

### Hierarchical clustering ###

# Reference: ISLR 10.5.2

df_hc <- simData

hc_complete <- hclust(dist(simData[!excludes]), method="complete") #Change method to "single" or "average" as needed

plot(hc_complete,main="Complete Linkage", xlab="", sub="",cex =.9)

df_hc$hc3 <- as.factor(cutree(hc_complete, 3))
df_hc$hc4 <- as.factor(cutree(hc_complete, 4))
df_hc$hc5 <- as.factor(cutree(hc_complete, 5))
df_hc$hc6 <- as.factor(cutree(hc_complete, 6))

hc3_plot <- ggplot(data= df_hc, aes(x=X1, y=X2, color=hc3))+geom_point()
hc4_plot <- ggplot(data= df_hc, aes(x=X1, y=X2, color=hc4))+geom_point()
hc5_plot <- ggplot(data= df_hc, aes(x=X1, y=X2, color=hc5))+geom_point()
hc6_plot <- ggplot(data= df_hc, aes(x=X1, y=X2, color=hc6))+geom_point()

grid.arrange(hc3_plot, hc4_plot, hc5_plot, hc6_plot)

```




